version: '3'
services:
        app:
                container_name: docker-react
                restart: always
                build: .
                ports:
                        - '3000:8000'
                links:
                        - mongo
        mongo:
                container_name: mongo
                image: mongo
                ports:
                        - '27017:27017'